# Generated by Django 5.0.1 on 2024-02-22 23:26

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Usuario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=200)),
                ('email', models.EmailField(max_length=200, unique=True)),
                ('senha', models.CharField(max_length=100)),
                ('cpf', models.IntegerField()),
                ('telefone', models.IntegerField()),
                ('cep', models.IntegerField()),
                ('endereco', models.CharField(max_length=200)),
                ('numero', models.CharField(max_length=100)),
                ('complemento', models.CharField(max_length=200)),
                ('bairro', models.CharField(max_length=100)),
                ('uf', models.CharField(max_length=10)),
                ('cidade', models.CharField(max_length=20)),
            ],
        ),
    ]
